spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_merchant_db
    username: admin
    password: abc123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # chỉ KIỂM TRA, tuyệt đối không tạo/sửa/xoá bảng
  flyway:
    enabled: true # Flyway là nơi DUY NHẤT tạo & đổi schema

  data:
    redis:
      host: localhost
      port: 6379
